"use client";

import { useCurrentAccount } from "@iota/dapp-kit";
import { useContract } from "@/hooks/useContract";
import { Button, Container, Heading, Text, TextField, Card, Flex, Box, Callout, Code, Separator, Grid } from "@radix-ui/themes";
import { useState } from "react";

// Import icon từ package root để Turbopack resolve ổn định
import { MagicWandIcon, MixerHorizontalIcon, Link2Icon, CheckCircledIcon, CrossCircledIcon, InfoCircledIcon, PlayIcon } from "@radix-ui/react-icons";

const SampleIntegration = () => {
  const currentAccount = useCurrentAccount();
  const { createHero, forgeSword, equipSword, heroId, swordId, hash, isLoading, error } = useContract();

  // State cho Hero
  const [heroName, setHeroName] = useState("DragonSlayer");
  const [heroImg, setHeroImg] = useState(`https://api.dicebear.com/9.x/adventurer/svg?seed=DragonSlayer`);

  // State cho Kiếm (Stats + Ảnh)
  const [stats, setStats] = useState({
    strength: "100",
    agility: "50",
    hp: "500",
    crit: "25",
    imgUrl: "https://cdn-icons-png.flaticon.com/512/1065/1065535.png" // Ảnh kiếm mặc định
  });

  // Hàm xử lý khi nhập tên Hero -> Tự động đổi ảnh avatar
  const handleNameChange = (e: any) => {
      const name = e.target.value;
      setHeroName(name);
      // Tạo ảnh ngẫu nhiên dựa trên tên (dùng Dicebear API)
      setHeroImg(`https://api.dicebear.com/9.x/adventurer/svg?seed=${name}`);
  }

  // Hàm xử lý thay đổi chỉ số kiếm
  const handleStatChange = (key: string, value: string) => {
    setStats(prev => ({ ...prev, [key]: value }));
  };

  if (!currentAccount) {
    return (
      <Container size="1" mt="6" p="4">
        <Callout.Root color="amber" variant="surface">
          <Callout.Icon><InfoCircledIcon /></Callout.Icon>
          <Callout.Text size="3" weight="bold">Please connect your wallet to play! 💼</Callout.Text>
        </Callout.Root>
      </Container>
    );
  }

  return (
    <Container size="2" mt="6" p="4">
      <Heading size="8" mb="2" align="center" style={{background: '-webkit-linear-gradient(45deg, #3086FF, #FF3030)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent'}}>
        ⚔️ RPG Dashboard
      </Heading>
      <Text align="center" color="gray" as="p" mb="5">Manage your Hero and Equipment on-chain with Images!</Text>
      
      <Separator my="4" size="4" />

      <Flex direction="column" gap="5">
        
        {/* --- 1. SUMMON HERO --- */}
        <Card size="3" variant="classic">
          <Flex direction="column" gap="3">
            <Heading size="4" color="blue">🦸 Step 1: Summon Hero</Heading>
            
            {/* Hiển thị Avatar Hero */}
            <Flex justify="center" align="center" direction="column" gap="2">
                <img 
                    src={heroImg} 
                    alt="Hero Preview" 
                    style={{width: '120px', height: '120px', borderRadius: '12px', border: '3px solid #3086FF', background: '#f0f0f0', objectFit: 'cover'}} 
                />
                <Text size="1" color="gray">Avatar generated by Name</Text>
            </Flex>

            <Flex gap="3" align="end">
              <Box style={{ flexGrow: 1 }}>
                <Text size="2" weight="bold" mb="1" as="div">Hero Name</Text>
                <TextField.Root size="3" value={heroName} onChange={handleNameChange} placeholder="Enter name..." />
              </Box>
              
              <Button size="3" onClick={() => createHero(heroName, heroImg)} disabled={isLoading || !!heroId} variant="solid">
                <MagicWandIcon /> {heroId ? "Summoned" : "Summon"}
              </Button>
            </Flex>

            {heroId && <Callout.Root color="blue" size="1" variant="surface"><Callout.Icon><CheckCircledIcon /></Callout.Icon><Callout.Text>ID: <Code>{heroId.slice(0, 10)}...</Code></Callout.Text></Callout.Root>}
          </Flex>
        </Card>

        {/* --- 2. FORGE SWORD --- */}
        <Card size="3" variant="classic">
          <Flex direction="column" gap="3">
            <Heading size="4" color="orange">🔨 Step 2: Forge Sword</Heading>
            
            <Grid columns="2" gap="3">
                <Box>
                    <Text size="2" weight="bold">Strength ⚔️</Text>
                    <TextField.Root type="number" value={stats.strength} onChange={(e) => handleStatChange('strength', e.target.value)} />
                </Box>
                <Box>
                    <Text size="2" weight="bold">Agility 👟</Text>
                    <TextField.Root type="number" value={stats.agility} onChange={(e) => handleStatChange('agility', e.target.value)} />
                </Box>
                <Box>
                    <Text size="2" weight="bold">HP ❤️</Text>
                    <TextField.Root type="number" value={stats.hp} onChange={(e) => handleStatChange('hp', e.target.value)} />
                </Box>
                <Box>
                    <Text size="2" weight="bold">Crit Rate ⚡</Text>
                    <TextField.Root type="number" value={stats.crit} onChange={(e) => handleStatChange('crit', e.target.value)} />
                </Box>
            </Grid>

            {/* Ô nhập Link ảnh Kiếm */}
            <Box mt="2">
                <Text size="2" weight="bold">Sword Image URL 🖼️</Text>
                <Flex gap="2" align="center">
                    <img src={stats.imgUrl} alt="Sword" style={{width: '40px', height: '40px', objectFit: 'contain', border: '1px solid #ccc', borderRadius: '4px'}} />
                    <TextField.Root style={{flexGrow: 1}} value={stats.imgUrl} onChange={(e) => handleStatChange('imgUrl', e.target.value)} placeholder="https://..." />
                </Flex>
            </Box>

            <Button size="3" color="orange" 
              onClick={() => forgeSword(stats.imgUrl, parseInt(stats.strength), parseInt(stats.agility), parseInt(stats.hp), parseInt(stats.crit))} 
                disabled={isLoading || !!swordId} variant="solid" style={{marginTop: '10px'}}>
                <MixerHorizontalIcon /> {swordId ? "Forged" : "Forge Sword"}
            </Button>
            
            {swordId && <Callout.Root color="orange" size="1" variant="surface"><Callout.Icon><CheckCircledIcon /></Callout.Icon><Callout.Text>ID: <Code>{swordId.slice(0, 10)}...</Code></Callout.Text></Callout.Root>}
          </Flex>
        </Card>

        {/* --- 3. EQUIP --- */}
        <Card size="4" style={{ background: 'var(--green-3)', border: '2px solid var(--green-9)' }}>
          <Flex direction="column" gap="4" align="center" py="2">
            <Heading size="6" color="green" weight="bold">⚔️ Step 3: Equip</Heading>
            <Text size="3" align="center" color="gray">Merge the Sword into the Hero</Text>
            <Button color="green" size="4" variant="solid" onClick={equipSword} disabled={!heroId || !swordId || isLoading} style={{ width: "100%", maxWidth: "400px", cursor: (!heroId || !swordId) ? "not-allowed" : "pointer" }}>
              <Link2Icon /> Equip Sword ➔
            </Button>
          </Flex>
        </Card>
      </Flex>

      {/* --- STATUS --- */}
      <Box mt="5">
        {isLoading && <Callout.Root color="gray"><Callout.Icon><PlayIcon /></Callout.Icon><Callout.Text>Processing...</Callout.Text></Callout.Root>}
        {error && <Callout.Root color="red"><Callout.Icon><CrossCircledIcon /></Callout.Icon><Callout.Text>Error: {error.message}</Callout.Text></Callout.Root>}
        {hash && <Callout.Root color="green"><Callout.Icon><CheckCircledIcon /></Callout.Icon><Callout.Text>Success! Hash: <Code>{hash.slice(0, 10)}...</Code></Callout.Text></Callout.Root>}
      </Box>
    </Container>
  );
};

export default SampleIntegration;